pipeline {
    agent any

    environment {
        RECIPIENTS = 'gnanendrachembeti9398@gmail.com'
        IMAGE_NAME = "my-java-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    parameters {
        string(name: 'BRANCH_TAG', defaultValue: 'main', description: 'Git Branch or Tag')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.BRANCH_TAG}", url: 'https://github.com/gnanendra9398/DEVOPS.git'
            }
        }

        stage('Build') {
            steps {
                dir('hello-java') { 
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('hello-java') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('hello-java') {
                    script {
                        sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    }
                }
            }
        }
        stage('Docker Login') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: 'jenkins',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_PASS'
                    )
                ]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh 'docker push "$IMAGE_NAME:${BUILD_NUMBER}"'
                    
                }
            }
        }
          stage('Notify') {
            steps {
                mail to: "${env.RECIPIENTS}",
                     subject: "Build Successful: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                     body: "Great news! The build completed successfully.\n\nJob: ${env.JOB_NAME}\nBuild Number: ${env.BUILD_NUMBER}\nBuild URL: ${env.BUILD_URL}"
            }
        }
    }
           post {
            failure {
              mail to: "${env.RECIPIENTS}",
                 subject: "Build Failed: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                 body: "Unfortunately, the build failed.\n\nJob: ${env.JOB_NAME}\nBuild Number: ${env.BUILD_NUMBER}\nCheck the console output at: ${env.BUILD_URL}"
        }
    } 
}
